export type CommunityPlatform = "whatsapp" | "telegram" | "facebook";

export type CommunityCategory =
  | "university"
  | "housing"
  | "scholarship"
  | "admissions"
  | "social"
  | "general";

export type CommunitySizeHint = "small" | "medium" | "large";

export const COMMUNITY_CHAPTERS = [
  "preparation",
  "housing",
  "university",
  "city-voice",
  "pan-italy",
] as const;

export type CommunityChapter = (typeof COMMUNITY_CHAPTERS)[number];

export interface CommunityLink {
  id: string;
  name: string;
  city: string | null;
  region: string | null;
  platform: CommunityPlatform;
  category: CommunityCategory;
  audience: string;
  description: string;
  url: string;
  editorialNote?: string;
  sizeHint?: CommunitySizeHint;
  status: "active" | "limited" | "unverified";
  verificationSource: "user-confirmed" | "editor-reviewed";
  lastCheckedAt: string; // YYYY-MM-DD
  chapter: CommunityChapter;
}

export const communityLinks: CommunityLink[] = [
  {
    id: "padova-community",
    name: "Padova Community",
    city: "Padova",
    region: "Veneto",
    platform: "whatsapp",
    category: "general",
    audience: "Padova'daki Turk ogrenciler ve adaylar",
    description: "Padova odakli genis ogrenci yardimlasma toplulugu.",
    url: "https://chat.whatsapp.com/HfGc4n67bRmBZpuBMmQr1A",
    editorialNote: "12 gruptan olusan buyuk bir community'nin parcasi.",
    sizeHint: "large",
    status: "active",
    verificationSource: "user-confirmed",
    lastCheckedAt: "2026-03-10",
    chapter: "city-voice",
  },
  {
    id: "firenze-whatsapp",
    name: "Firenze WhatsApp Grubu",
    city: "Firenze",
    region: "Toscana",
    platform: "whatsapp",
    category: "general",
    audience: "Firenze'deki Turk ogrenciler ve adaylar",
    description: "Firenze icin genel yardimlasma ve bilgi paylasim grubu.",
    url: "https://chat.whatsapp.com/DgmmBrA1ukI2MZ0iUJZB4k",
    sizeHint: "medium",
    status: "active",
    verificationSource: "user-confirmed",
    lastCheckedAt: "2026-03-10",
    chapter: "city-voice",
  },
  {
    id: "pre-enrollment-yardimlasma",
    name: "Pre Enrollment Yardimlasma",
    city: null,
    region: null,
    platform: "whatsapp",
    category: "admissions",
    audience: "Pre-enrollment surecine giren ogrenciler",
    description: "Pre-enrollment sureci icin bilgi paylasimi ve yardimlasma grubu.",
    url: "https://chat.whatsapp.com/B9cMj3Iir98G1e132UU1bz",
    sizeHint: "medium",
    status: "active",
    verificationSource: "user-confirmed",
    lastCheckedAt: "2026-03-10",
    chapter: "preparation",
  },
  {
    id: "ergo-yardimlasma",
    name: "ER.GO Yardimlasma",
    city: null,
    region: "Emilia-Romagna",
    platform: "whatsapp",
    category: "scholarship",
    audience: "ER.GO burs ve hak sureclerini takip eden ogrenciler",
    description: "ER.GO odakli burs ve ogrenci destek surecleri icin yardimlasma grubu.",
    url: "https://chat.whatsapp.com/KlMYASxuF4V67Ix5LZvNaE",
    sizeHint: "medium",
    status: "active",
    verificationSource: "user-confirmed",
    lastCheckedAt: "2026-03-10",
    chapter: "preparation",
  },
  {
    id: "roma-ev-oda",
    name: "Roma Ev/Oda",
    city: "Roma",
    region: "Lazio",
    platform: "whatsapp",
    category: "housing",
    audience: "Roma'da ev veya oda arayan ogrenciler",
    description: "Roma icin ev, oda ve konaklama paylasim grubu.",
    url: "https://chat.whatsapp.com/KPbFz7uqMDz3AuxN4M1Ti7",
    editorialNote: "9 gruptan olusan daha buyuk bir community'nin parcasi.",
    sizeHint: "large",
    status: "active",
    verificationSource: "user-confirmed",
    lastCheckedAt: "2026-03-10",
    chapter: "housing",
  },
  {
    id: "bologna-hiking-club",
    name: "Bologna Hiking Club",
    city: "Bologna",
    region: "Emilia-Romagna",
    platform: "whatsapp",
    category: "social",
    audience: "Bologna'daki sosyal cevre arayan ogrenciler",
    description: "Bologna merkezli sosyal etkinlik ve tanisma toplulugu.",
    url: "https://chat.whatsapp.com/Cx7sSHAC4JkGaXXMgTiXNj",
    sizeHint: "medium",
    status: "active",
    verificationSource: "user-confirmed",
    lastCheckedAt: "2026-03-10",
    chapter: "city-voice",
  },
  {
    id: "bologna-erasmus-students",
    name: "Bologna - Erasmus Students",
    city: "Bologna",
    region: "Emilia-Romagna",
    platform: "facebook",
    category: "social",
    audience: "Bologna'daki Erasmus ogrencileri ve uluslararasi ogrenci cevresi arayanlar",
    description: "Bologna merkezli Erasmus ve uluslararasi ogrenciler icin sosyal paylasim toplulugu.",
    url: "https://www.facebook.com/groups/9481808533/",
    sizeHint: "medium",
    status: "active",
    verificationSource: "user-confirmed",
    lastCheckedAt: "2026-03-10",
    chapter: "city-voice",
  },
  {
    id: "unibo-general",
    name: "UNIBO",
    city: "Bologna",
    region: "Emilia-Romagna",
    platform: "whatsapp",
    category: "university",
    audience: "University of Bologna ogrencileri ve adaylari",
    description: "UNIBO odakli genel iletisim ve yardimlasma grubu.",
    url: "https://chat.whatsapp.com/DRnopfSvsWx7tuKpRxs4Mm",
    sizeHint: "large",
    status: "active",
    verificationSource: "user-confirmed",
    lastCheckedAt: "2026-03-10",
    chapter: "university",
  },
  {
    id: "househunters-ravenna",
    name: "Househunters Ravenna",
    city: "Ravenna",
    region: "Emilia-Romagna",
    platform: "whatsapp",
    category: "housing",
    audience: "Ravenna'da konaklama arayan ogrenciler",
    description: "Ravenna icin ev ve oda arama odakli konaklama grubu.",
    url: "https://chat.whatsapp.com/IaSkRBr1YhkKzpQrm6JO3r",
    sizeHint: "medium",
    status: "active",
    verificationSource: "user-confirmed",
    lastCheckedAt: "2026-03-10",
    chapter: "housing",
  },
  {
    id: "apartments-bologna",
    name: "Apartments Bologna",
    city: "Bologna",
    region: "Emilia-Romagna",
    platform: "facebook",
    category: "housing",
    audience: "Bologna'da ev veya oda arayan ogrenciler",
    description: "Bologna icin apartman, ev ve oda paylasimlarina odaklanan konaklama toplulugu.",
    url: "https://www.facebook.com/groups/apartments.bologna/",
    sizeHint: "medium",
    status: "active",
    verificationSource: "user-confirmed",
    lastCheckedAt: "2026-03-10",
    chapter: "housing",
  },
  {
    id: "spotted-unibo-ravenna",
    name: "Spotted.Unibo.Ravenna",
    city: "Ravenna",
    region: "Emilia-Romagna",
    platform: "telegram",
    category: "social",
    audience: "Ravenna'daki ogrenciler ve adaylar",
    description: "Ravenna ogrenci cevresi icin sosyal ve genel paylasim kanali.",
    url: "https://t.me/+7RtXwlf3vSJiNTY8?fbclid=PAZXh0bgNhZW0CMTEAAab9XGAHpw9qe8Lc7ZHUJQDCkjOCZvhNwwChuuw85ZrE0H4DVQwbZ2lJtDg_aem_AWx4Qoq0oLlbxPERYi3mB0lQFrUxkps9ZnKFsszua4vwLe-llALvndSsNOgQ4_rOU0TBrrpSKB2VkNYNMWyx6pGI",
    sizeHint: "medium",
    status: "active",
    verificationSource: "user-confirmed",
    lastCheckedAt: "2026-03-10",
    chapter: "city-voice",
  },
  {
    id: "italyada-yasayan-turkler",
    name: "Italyada yasayan Turkler",
    city: null,
    region: null,
    platform: "facebook",
    category: "general",
    audience: "Italya'da yasayan Turkler ve Italya'ya gelmeyi planlayanlar",
    description: "Italya'daki Turk toplulugu icin genel paylasim ve yardimlasma grubu.",
    url: "https://www.facebook.com/groups/italyaturkiye/?sorting_setting=CHRONOLOGICAL",
    editorialNote: "Kucuk grup.",
    sizeHint: "small",
    status: "active",
    verificationSource: "user-confirmed",
    lastCheckedAt: "2026-03-10",
    chapter: "pan-italy",
  },
  {
    id: "italya-bilgi",
    name: "Italya Bilgi",
    city: null,
    region: null,
    platform: "facebook",
    category: "general",
    audience: "Italya hakkinda bilgi arayan Turk ogrenciler ve adaylar",
    description: "Italya odakli genel bilgi paylasimi ve yardimlasma toplulugu.",
    url: "https://www.facebook.com/groups/1876789549157921/",
    sizeHint: "medium",
    status: "active",
    verificationSource: "user-confirmed",
    lastCheckedAt: "2026-03-10",
    chapter: "pan-italy",
  },
  {
    id: "sapienza-general",
    name: "Sapienza",
    city: "Roma",
    region: "Lazio",
    platform: "whatsapp",
    category: "university",
    audience: "Sapienza ogrencileri ve adaylari",
    description: "Sapienza odakli genel ogrenci yardimlasma grubu.",
    url: "https://chat.whatsapp.com/ElRyVEOfAVR6Np17fs5one",
    sizeHint: "large",
    status: "active",
    verificationSource: "user-confirmed",
    lastCheckedAt: "2026-03-10",
    chapter: "university",
  },
  {
    id: "accomodations-in-rome-2025-2026",
    name: "ACCOMODATIONS IN ROME 2025/2026",
    city: "Roma",
    region: "Lazio",
    platform: "facebook",
    category: "housing",
    audience: "Roma'da 2025/2026 donemi icin ev veya oda arayan ogrenciler",
    description: "Roma odakli konaklama paylasimlari ve ev/oda arayisina yonelik Facebook toplulugu.",
    url: "https://www.facebook.com/groups/250512498745722/",
    sizeHint: "medium",
    status: "active",
    verificationSource: "user-confirmed",
    lastCheckedAt: "2026-03-10",
    chapter: "housing",
  },
  {
    id: "unito-23-24",
    name: "Unito 23/24",
    city: "Torino",
    region: "Piemonte",
    platform: "whatsapp",
    category: "university",
    audience: "University of Torino ogrencileri ve adaylari",
    description: "Unito icin daha kucuk olcekli yardimlasma grubu.",
    url: "https://chat.whatsapp.com/ERE1aefGS9x5dL4w5oygzI",
    editorialNote: "Kucuk grup.",
    sizeHint: "small",
    status: "active",
    verificationSource: "user-confirmed",
    lastCheckedAt: "2026-03-10",
    chapter: "university",
  },
  {
    id: "unito-22-23",
    name: "Unito 22/23",
    city: "Torino",
    region: "Piemonte",
    platform: "whatsapp",
    category: "university",
    audience: "University of Torino ogrencileri ve adaylari",
    description: "Unito icin daha kucuk olcekli yardimlasma grubu.",
    url: "https://chat.whatsapp.com/EgzxdMK8Xp0JueH3tVG9xZ",
    editorialNote: "Kucuk grup.",
    sizeHint: "small",
    status: "active",
    verificationSource: "user-confirmed",
    lastCheckedAt: "2026-03-10",
    chapter: "university",
  },
  {
    id: "sapienza-2026-2027",
    name: "Sapienza 2026/2027",
    city: "Roma",
    region: "Lazio",
    platform: "whatsapp",
    category: "university",
    audience: "2026/2027 donemi Sapienza adaylari",
    description: "Sapienza 2026/2027 cohort odakli buyuk yardimlasma grubu.",
    url: "https://chat.whatsapp.com/LGvVQpeP5XiIdT0JpMeVjO",
    editorialNote: "Buyuk grup; zaman zaman dolu olabilir, periyodik temizlik yapiliyor.",
    sizeHint: "large",
    status: "limited",
    verificationSource: "user-confirmed",
    lastCheckedAt: "2026-03-10",
    chapter: "university",
  },
  {
    id: "ergo-burs-basvuru-sureci",
    name: "ERGO Burs Basvuru Sureci",
    city: null,
    region: "Emilia-Romagna",
    platform: "whatsapp",
    category: "scholarship",
    audience: "ER.GO burs basvurusu yapan ogrenciler",
    description: "ER.GO burs basvuru sureci odakli yardimlasma grubu.",
    url: "https://chat.whatsapp.com/LdhXrjE7PVb553mITz2fNt",
    editorialNote: "Kucuk grup.",
    sizeHint: "small",
    status: "active",
    verificationSource: "user-confirmed",
    lastCheckedAt: "2026-03-10",
    chapter: "preparation",
  },
];

export const COMMUNITY_LINKS: CommunityLink[] = communityLinks;
