import type { CityDetail } from "@/types/cities";

export const CURATED_CITIES: CityDetail[] = [
  {
    slug: "milano",
    name: "Milano",
    nameEn: "Milan",
    region: "Lombardia",
    costSourceName: "Numbeo",
    costSourceUrl: "https://www.numbeo.com/cost-of-living/in/Milan",
    costSourceLastUpdated: "2026-05-23",
    costRating: 5,
    studentPopulation: "Çok Yüksek (>85.000)",
    studentPopulationEn: "Very High (>85,000)",
    rentAverage: "1 odalı daire: merkezde ~1.468,75€ | merkez dışında ~1.045,17€",
    rentAverageEn: "1-bedroom apartment: ~€1,468.75 in the city centre | ~€1,045.17 outside the centre",
    livingExpenses: "Ucuz restoran: ~20€ | Cappuccino: ~1,91€ | 85 m² temel faturalar: ~220,21€",
    livingExpensesEn: "Inexpensive meal: ~€20 | Cappuccino: ~€1.91 | Basic utilities for 85 m²: ~€220.21",
    transportCost: "Tek yön şehir içi bilet: ~2,20€",
    transportCostEn: "One-way local transport ticket: ~€2.20",
    transportDetails: "4 aktif metro hattı (M1, M2, M3, M5), son derece geniş tramvay ve otobüs ağı. Malpensa, Linate ve Bergamo (Orio al Serio) olmak üzere 3 büyük havalimanı bağlantısı mevcuttur.",
    transportDetailsEn: "4 active metro lines (M1, M2, M3, M5), extensive tram and bus network. Directly connected to 3 airports: Malpensa, Linate, and Bergamo (Orio al Serio).",
    climateAndVibe: "Kışlar soğuk ve sisli, yazlar ise sıcak ve nemlidir. İtalya'nın finans, moda ve tasarım merkezidir. Hızlı, dinamik ve Avrupa standartlarında kozmopolit bir metropol yaşantısı sunar. Sosyal hayat, kültürel etkinlikler ve kariyer fırsatları zirvededir.",
    climateAndVibeEn: "Winters are cold and foggy, summers are warm and humid. Milan is Italy's financial, fashion, and design powerhouse. It offers a fast-paced, dynamic, and highly cosmopolitan metropolitan environment with outstanding career opportunities.",
    editorialTip: "Ev bulma rekabeti aşırı yüksektir; kabulünüz gelir gelmez okul yurtlarına veya Spotahome/Uniplaces gibi doğrulanmış platformlara hemen başvurun. Ulaşım kartınızı online olarak ATM portalından ilk hafta sipariş edin.",
    editorialTipEn: "Housing competition is extremely high; apply for university accommodation or platforms like Spotahome/Uniplaces as soon as admitted. Order your ATM student card online during your first week."
  },
  {
    slug: "roma",
    name: "Roma",
    nameEn: "Rome",
    region: "Lazio",
    costSourceName: "Numbeo",
    costSourceUrl: "https://www.numbeo.com/cost-of-living/in/Rome",
    costSourceLastUpdated: "2026-05-21",
    costRating: 4,
    studentPopulation: "Çok Yüksek (>90.000)",
    studentPopulationEn: "Very High (>90,000)",
    rentAverage: "1 odalı daire: merkezde ~1.076,92€ | merkez dışında ~778,57€",
    rentAverageEn: "1-bedroom apartment: ~€1,076.92 in the city centre | ~€778.57 outside the centre",
    livingExpenses: "Ucuz restoran: ~15€ | Cappuccino: ~1,94€ | 85 m² temel faturalar: ~183,63€",
    livingExpensesEn: "Inexpensive meal: ~€15 | Cappuccino: ~€1.94 | Basic utilities for 85 m²: ~€183.63",
    transportCost: "Tek yön şehir içi bilet: ~1,50€",
    transportCostEn: "One-way local transport ticket: ~€1.50",
    transportDetails: "3 aktif metro hattı (A, B, C) ve geniş otobüs ağları. Şehir içi otobüslerde trafik nedeniyle gecikmeler yaşanabilir. Fiumicino (FCO) ve Ciampino (CIA) havalimanlarına doğrudan tren/otobüs hatları bulunur.",
    transportDetailsEn: "3 active metro lines (A, B, C) and vast bus networks. Bus routes can be affected by city traffic. Connected directly to Fiumicino (FCO) and Ciampino (CIA) airports via express train/bus lines.",
    climateAndVibe: "Yumuşak Akdeniz iklimi. Kışlar ılık geçer, yazlar ise oldukça sıcaktır. 'Açık hava müzesi' olan şehir, binlerce yıllık tarihi dokusuyla öğrencilere büyüleyici bir hayat sunar. Hayat Milano'ya göre daha yavaş, daha rahat ve Akdeniz ruhuna uygundur.",
    climateAndVibeEn: "Mild Mediterranean climate. Warm, sunny summers and mild winters. Living in Rome is like studying in an open-air museum, offering a mesmerizing historic setting. The pace of life is slower and more relaxed compared to Milan.",
    editorialTip: "Otobüs gecikmelerine alışın ve kampüsünüze yakın veya metro hatlarına (A/B) yürüme mesafesinde ev kiralamaya özen gösterin. Yıllık abonman kartı almak aylık kartlara göre çok daha ekonomiktir.",
    editorialTipEn: "Adapt to bus delays and prioritize renting near Metro A/B lines or your campus. Purchasing the annual student transit card is significantly cheaper than buying monthly ones."
  },
  {
    slug: "bologna",
    name: "Bologna",
    nameEn: "Bologna",
    region: "Emilia-Romagna",
    costSourceName: "Numbeo",
    costSourceUrl: "https://www.numbeo.com/cost-of-living/in/Bologna",
    costSourceLastUpdated: "2026-05-11",
    costRating: 4,
    studentPopulation: "Yüksek (>80.000)",
    studentPopulationEn: "High (>80,000)",
    rentAverage: "1 odalı daire: merkezde ~966,33€ | merkez dışında ~775,54€",
    rentAverageEn: "1-bedroom apartment: ~€966.33 in the city centre | ~€775.54 outside the centre",
    livingExpenses: "Ucuz restoran: ~20€ | Cappuccino: ~1,92€ | 85 m² temel faturalar: ~217,50€",
    livingExpensesEn: "Inexpensive meal: ~€20 | Cappuccino: ~€1.92 | Basic utilities for 85 m²: ~€217.50",
    transportCost: "Tek yön şehir içi bilet: ~2,30€",
    transportCostEn: "One-way local transport ticket: ~€2.30",
    transportDetails: "Metro yoktur. Şehir içi ulaşım mükemmel işleyen TPER otobüs hatları ve bisiklet yollarıyla sağlanır. Bologna Centrale istasyonu İtalya'nın en büyük tren kavşağıdır, her şehre hızlı tren bulunur. Havalimanına Marconi Express ile 7 dakikada gidilir.",
    transportDetailsEn: "No metro. Public transit relies on excellent TPER buses, extensive bike lanes, and walking. Bologna Centrale is Italy's primary rail hub, making weekend trips to any city extremely easy. Marconi Airport is 7 mins away via Marconi Express.",
    climateAndVibe: "Dört mevsim belirgindir. Kışları serin, yazları sıcaktır. Dünyanın en eski üniversitesine (1088) ev sahipliği yapar. Şehir nüfusunun büyük kısmını öğrenciler oluşturduğu için tam bir öğrenci şehridir. Tarihi revaklar (portici), canlı sokak festivalleri ve soluksuz öğrenci aktiviteleriyle ünlüdür.",
    climateAndVibeEn: "Four distinct seasons; chilly winters and warm summers. Home to the world's oldest university (1088). A true university city where students dominate the population. Renowned for its UNESCO-protected porticoes, vibrant street life, and unmatched student culture.",
    editorialTip: "Bologna'da ev bulmak bazen İtalya'nın en zor sürecine dönüşebilir; ev aramaya Haziran ayında başlayın. Şehirde ulaşım için mutlaka ikinci el bir bisiklet edinin, otobüsten çok daha fazla kullanacaksınız.",
    editorialTipEn: "Finding accommodation in Bologna can be incredibly tough; start your search in early June. Get a second-hand bicycle as soon as you arrive, as it is the absolute best way to navigate the city."
  },
  {
    slug: "torino",
    name: "Torino",
    nameEn: "Turin",
    region: "Piemonte",
    costSourceName: "Numbeo",
    costSourceUrl: "https://www.numbeo.com/cost-of-living/in/Turin",
    costSourceLastUpdated: "2026-05-17",
    costRating: 3,
    studentPopulation: "Yüksek (>70.000)",
    studentPopulationEn: "High (>70,000)",
    rentAverage: "1 odalı daire: merkezde ~738,89€ | merkez dışında ~546,85€",
    rentAverageEn: "1-bedroom apartment: ~€738.89 in the city centre | ~€546.85 outside the centre",
    livingExpenses: "Ucuz restoran: ~18€ | Cappuccino: ~1,72€ | 85 m² temel faturalar: ~204,72€",
    livingExpensesEn: "Inexpensive meal: ~€18 | Cappuccino: ~€1.72 | Basic utilities for 85 m²: ~€204.72",
    transportCost: "Tek yön şehir içi bilet: ~1,90€",
    transportCostEn: "One-way local transport ticket: ~€1.90",
    transportDetails: "1 sürücüsüz metro hattı, tarihi ve yaygın tramvay ağı, modern otobüsler. Tren istasyonlarından (Porta Nuova / Porta Susa) Milano'ya 1 saatte hızlı tren mevcuttur. Torino Caselle havalimanı trenle doğrudan şehre bağlıdır.",
    transportDetailsEn: "1 automated driverless metro line, extensive historic tramway system, and buses. High-speed trains reach Milan in just 1 hour from Porta Nuova/Porta Susa stations. Torino Caselle airport is connected to the city center.",
    climateAndVibe: "Alplere yakınlığı nedeniyle kışlar oldukça soğuk ve karlı geçebilir; yazlar ise ılımandır. Eski İtalya krallığının başkenti olan şehir görkemli sarayları, geniş bulvarları ve düzenli ızgara planı ile çok asildir. Politecnico di Torino ve UniTo sayesinde teknoloji ve mühendislik öğrencileriyle doludur.",
    climateAndVibeEn: "Chilly, snowy winters due to the nearby Alps; mild and pleasant summers. Former capital of the Kingdom of Italy, featuring regal baroque palaces and beautiful boulevards. Powered by UniTo and PoliTo, it is a bustling hub for engineering and science students.",
    editorialTip: "Kuzey İtalya'da yaşayıp bütçesini korumak isteyen öğrenciler için en ideal şehirdir. San Salvario bölgesi gece hayatı ve öğrenci mekanları için popülerdir ancak daha sakin bir çalışma alanı için Crocetta veya Cenisia bölgelerini tercih edin.",
    editorialTipEn: "Torino is the ultimate option for students wanting Northern Italian quality of life at affordable rates. San Salvario is famous for nightlife, while Crocetta or Cenisia are ideal for peaceful studying."
  },
  {
    slug: "floransa",
    name: "Floransa",
    nameEn: "Florence",
    region: "Toscana",
    costSourceName: "Numbeo",
    costSourceUrl: "https://www.numbeo.com/cost-of-living/in/Florence",
    costSourceLastUpdated: "2026-05-21",
    costRating: 4,
    studentPopulation: "Yüksek",
    studentPopulationEn: "High",
    rentAverage: "1 odalı daire: merkezde ~1.230€ | merkez dışında ~844,77€",
    rentAverageEn: "1-bedroom apartment: ~€1,230 in the city centre | ~€844.77 outside the centre",
    livingExpenses: "Ucuz restoran: ~22€ | Cappuccino: ~1,99€ | 85 m² temel faturalar: ~199,84€",
    livingExpensesEn: "Inexpensive meal: ~€22 | Cappuccino: ~€1.99 | Basic utilities for 85 m²: ~€199.84",
    transportCost: "Tek yön şehir içi bilet: ~1,70€",
    transportCostEn: "One-way local transport ticket: ~€1.70",
    transportDetails: "Şehir içi ulaşım T1/T2 tramvay hatları, Autolinee Toscane otobüsleri ve Santa Maria Novella merkezli tren bağlantılarıyla çalışır. Tarihi merkez kompakt olduğu için günlük rotalarda yürüyüş ve tramvay birlikte kullanılır.",
    transportDetailsEn: "Local transit uses the T1/T2 tram lines, Autolinee Toscane buses, and rail links centered on Santa Maria Novella. The historic centre is compact, so daily routes often combine walking with tram travel.",
    climateAndVibe: "Rönesans mirası, yoğun turizm ve güçlü sanat-tasarım atmosferiyle Floransa çok karakterli ama pahalı bir öğrenci şehridir. Şehir merkezi etkileyicidir; günlük yaşamda kalabalık ve konut rekabeti hesaba katılmalıdır.",
    climateAndVibeEn: "Florence is a highly distinctive but expensive student city shaped by Renaissance heritage, heavy tourism, and a strong art and design atmosphere. The centre is stunning, but crowds and housing competition matter in daily life.",
    editorialTip: "Tarihi merkezde kiralar hızlı yükselir; kampüs, tramvay hattı ve Santa Maria Novella bağlantısını birlikte düşünün. Novoli ve Rifredi gibi daha pratik bölgeleri merkezle mutlaka karşılaştırın.",
    editorialTipEn: "Rents rise quickly in the historic centre, so compare housing by campus access, tram links, and Santa Maria Novella connections. Practical areas such as Novoli and Rifredi are worth weighing against the centre."
  },
  {
    slug: "venedik",
    name: "Venedik",
    nameEn: "Venice",
    region: "Veneto",
    costSourceName: "Numbeo",
    costSourceUrl: "https://www.numbeo.com/cost-of-living/in/Venice",
    costSourceLastUpdated: "2026-05-04",
    costRating: 4,
    studentPopulation: "Orta-Yüksek",
    studentPopulationEn: "Medium-High",
    rentAverage: "1 odalı daire: merkezde ~1.126€ | merkez dışında ~637,50€",
    rentAverageEn: "1-bedroom apartment: ~€1,126 in the city centre | ~€637.50 outside the centre",
    livingExpenses: "Ucuz restoran: ~20€ | Cappuccino: ~1,97€ | 85 m² temel faturalar: ~242€",
    livingExpensesEn: "Inexpensive meal: ~€20 | Cappuccino: ~€1.97 | Basic utilities for 85 m²: ~€242",
    transportCost: "Tek yön şehir içi bilet: ~1,50€",
    transportCostEn: "One-way local transport ticket: ~€1.50",
    transportDetails: "Tarihi merkezde günlük ulaşım yürüyüş, vaporetto su otobüsleri ve Santa Lucia bağlantılarıyla ilerler. Mestre tarafı ise tren, otobüs ve tramvay bağlantıları sayesinde daha pratik ve bütçe dostu bir öğrenci üssü olabilir.",
    transportDetailsEn: "In the historic centre, daily mobility relies on walking, vaporetto water buses, and Santa Lucia rail links. Mestre can be a more practical and budget-friendly student base thanks to train, bus, and tram connections.",
    climateAndVibe: "Lagün üzerindeki tarihi atmosfer benzersizdir; ancak turizm yoğunluğu ve ada yaşamının lojistiği günlük hayatı pahalı ve planlı hale getirir. Sanat, mimarlık ve kültür odaklı öğrenciler için çok güçlü bir şehir deneyimi sunar.",
    climateAndVibeEn: "The lagoon setting is unique, but tourism pressure and island logistics make daily life more expensive and planning-heavy. It is a powerful city experience for students focused on art, architecture, and culture.",
    editorialTip: "Tarihi adada yaşamak cazip ama pahalı olabilir; Mestre, Marghera ve tren/vaporetto bağlantısı güçlü bölgeleri mutlaka kıyaslayın. Ulaşım bütçesini yalnız kira kadar ciddiye almak gerekir.",
    editorialTipEn: "Living on the historic island is tempting but can be expensive; compare Mestre, Marghera, and areas with strong train or vaporetto links. Treat the transport budget as seriously as the rent budget."
  },
  {
    slug: "verona",
    name: "Verona",
    nameEn: "Verona",
    region: "Veneto",
    costSourceName: "Numbeo",
    costSourceUrl: "https://www.numbeo.com/cost-of-living/in/Verona",
    costSourceLastUpdated: "2026-05-18",
    costRating: 3,
    studentPopulation: "Orta",
    studentPopulationEn: "Medium",
    rentAverage: "1 odalı daire: merkezde ~868,33€ | merkez dışında ~606,67€",
    rentAverageEn: "1-bedroom apartment: ~€868.33 in the city centre | ~€606.67 outside the centre",
    livingExpenses: "Ucuz restoran: ~18€ | Cappuccino: ~1,83€ | 85 m² temel faturalar: ~172,39€",
    livingExpensesEn: "Inexpensive meal: ~€18 | Cappuccino: ~€1.83 | Basic utilities for 85 m²: ~€172.39",
    transportCost: "Tek yön şehir içi bilet: ~1,80€",
    transportCostEn: "One-way local transport ticket: ~€1.80",
    transportDetails: "Şehir içi ulaşım otobüs hatları, Verona Porta Nuova tren istasyonu ve yürünebilir tarihi merkez etrafında şekillenir. Merkez dışı mahallelerde ev bakarken otobüs sıklığı ve istasyon bağlantısını birlikte kontrol etmek gerekir.",
    transportDetailsEn: "Local mobility is shaped around bus lines, Verona Porta Nuova railway station, and a walkable historic centre. When looking outside the centre, check bus frequency and station access together.",
    climateAndVibe: "Verona, Veneto içinde tarihi dokusu güçlü ama büyük metropollere göre daha sakin bir öğrenci deneyimi sunar. Turistik merkez, yerel mahalle yaşamı ve kuzey İtalya ulaşım bağlantıları dengeli bir günlük ritim yaratır.",
    climateAndVibeEn: "Verona offers a historic but calmer student experience within Veneto compared with large metropolitan cities. Its tourist centre, local neighborhood life, and northern Italian transport links create a balanced daily rhythm.",
    editorialTip: "Tarihi merkeze yakın olmak sosyal hayatı kolaylaştırır, ama kira farkı için merkez dışı seçenekleri Porta Nuova ve sık otobüs hatlarıyla birlikte kıyaslayın.",
    editorialTipEn: "Living near the historic centre makes social life easier, but compare outside-centre options through Porta Nuova access and frequent bus routes before accepting the rent premium."
  },
  {
    slug: "padova",
    name: "Padova",
    nameEn: "Padua",
    region: "Veneto",
    costSourceName: "Numbeo",
    costSourceUrl: "https://www.numbeo.com/cost-of-living/in/Padova",
    costSourceLastUpdated: "2026-05-11",
    costRating: 3,
    studentPopulation: "Orta-Yüksek (>65.000)",
    studentPopulationEn: "Medium-High (>65,000)",
    rentAverage: "1 odalı daire: merkezde ~956,44€ | merkez dışında ~732,89€",
    rentAverageEn: "1-bedroom apartment: ~€956.44 in the city centre | ~€732.89 outside the centre",
    livingExpenses: "Ucuz restoran: ~20€ | Cappuccino: ~1,79€ | 85 m² temel faturalar: ~226,13€",
    livingExpensesEn: "Inexpensive meal: ~€20 | Cappuccino: ~€1.79 | Basic utilities for 85 m²: ~€226.13",
    transportCost: "Tek yön şehir içi bilet: ~1,70€",
    transportCostEn: "One-way local transport ticket: ~€1.70",
    transportDetails: "Mükemmel çalışan tek raylı tramvay (Translohr) ve otobüs hatları. Venedik'e trenle sadece 25-30 dakika mesafededir. Venedik Marco Polo ve Treviso havalimanlarına doğrudan otobüs bağlantıları mevcuttur.",
    transportDetailsEn: "Highly efficient single-rail tram (Translohr) and buses. Located just 25-30 minutes away from Venice by regional train. Directly connected to Venice Marco Polo and Treviso airports by regular bus services.",
    climateAndVibe: "Nemli ılıman iklim; kışları serin ve yağışlı, yazları sıcaktır. İtalya'nın en köklü ikinci üniversitesine (1222) ev sahipliği yapar. Şehir merkezindeki Piazza delle Erbe ve Piazza della Frutta çevresi her akşam binlerce öğrencinin 'Spritz' eşliğinde buluştuğu harika bir atmosfere sahiptir.",
    climateAndVibeEn: "Humid temperate climate; cool, rainy winters and warm summers. Home to Italy's second-oldest university (1222). The squares (Piazza delle Erbe & Piazza della Frutta) host thousands of students gathering every evening, creating a magnificent social atmosphere.",
    editorialTip: "Ulaşım için bisiklet Padova'da hayatidir, neredeyse herkes bisiklet kullanır. Gelir gelmez yerel öğrenci pazarlarından veya ikinci el gruplarından uygun fiyatlı bir bisiklet ve sağlam bir kilit edinin.",
    editorialTipEn: "Bicycles are a way of life in Padua. Buy a cheap second-hand bike and a very strong lock immediately upon arrival to cruise around like a local."
  },
  {
    slug: "parma",
    name: "Parma",
    nameEn: "Parma",
    region: "Emilia-Romagna",
    costSourceName: "Numbeo",
    costSourceUrl: "https://www.numbeo.com/cost-of-living/in/Parma",
    costSourceLastUpdated: "2026-05-04",
    costRating: 3,
    studentPopulation: "Orta",
    studentPopulationEn: "Medium",
    rentAverage: "1 odalı daire: merkezde ~790€ | merkez dışında ~578€",
    rentAverageEn: "1-bedroom apartment: ~€790 in the city centre | ~€578 outside the centre",
    livingExpenses: "Ucuz restoran: ~18€ | Cappuccino: ~2,20€ | 85 m² temel faturalar: ~209,85€",
    livingExpensesEn: "Inexpensive meal: ~€18 | Cappuccino: ~€2.20 | Basic utilities for 85 m²: ~€209.85",
    transportCost: "Tek yön şehir içi bilet: ~1,70€",
    transportCostEn: "One-way local transport ticket: ~€1.70",
    transportDetails: "Şehir içi ulaşım ağırlıkla otobüs hatları ve tren istasyonu etrafındaki bölgesel bağlantılarla ilerler. Merkez kompakt olduğu için günlük öğrenci rotalarında yürüyüş ve bisiklet de pratik seçeneklerdir.",
    transportDetailsEn: "Local mobility relies mostly on bus lines and regional rail connections around the main station. The centre is compact, so walking and cycling are practical options for everyday student routes.",
    climateAndVibe: "Emilia-Romagna içinde daha sakin, düzenli ve gastronomi kültürü güçlü bir şehir deneyimi sunar. Büyük metropollere göre tempo daha yavaştır; bu da odaklı ve yerel bir öğrenci hayatı isteyenler için avantajdır.",
    climateAndVibeEn: "Parma offers a calmer, orderly student experience in Emilia-Romagna with a strong food culture. The pace is slower than in large metropolitan cities, which can suit students looking for a focused and local daily life.",
    editorialTip: "Ev seçerken sadece merkeze yakınlığa değil, kampüs ve tren istasyonu bağlantısına da bakın. Parma'da merkez dışı seçenekler kira bütçesini ciddi şekilde rahatlatabilir.",
    editorialTipEn: "When choosing housing, check campus and station access rather than centrality alone. Outside-centre options in Parma can make the rent budget noticeably easier to manage."
  },
  {
    slug: "pisa",
    name: "Pisa",
    nameEn: "Pisa",
    region: "Toscana",
    costSourceName: "Numbeo",
    costSourceUrl: "https://www.numbeo.com/cost-of-living/in/Pisa",
    costSourceLastUpdated: "2026-05-10",
    costRating: 3,
    studentPopulation: "Orta (>50.000)",
    studentPopulationEn: "Medium (>50,000)",
    rentAverage: "1 odalı daire: merkezde ~903,54€ | merkez dışında ~706,76€",
    rentAverageEn: "1-bedroom apartment: ~€903.54 in the city centre | ~€706.76 outside the centre",
    livingExpenses: "Ucuz restoran: ~17€ | Cappuccino: ~1,79€ | 85 m² temel faturalar: ~320€",
    livingExpensesEn: "Inexpensive meal: ~€17 | Cappuccino: ~€1.79 | Basic utilities for 85 m²: ~€320",
    transportCost: "Tek yön şehir içi bilet: ~2€",
    transportCostEn: "One-way local transport ticket: ~€2",
    transportDetails: "Metro yoktur. Şehir küçük olduğu için toplu taşımaya neredeyse hiç ihtiyaç duyulmaz; yürüyerek veya bisikletle her yere ulaşılabilir. Galileo Galilei Havalimanı (PSA) Toskana'nın ana havalimanıdır ve şehre yürüyerek bile gidilebilecek kadar yakındır (Pisa Mover ile 5 dk).",
    transportDetailsEn: "No metro needed. The city is incredibly compact; walking or cycling is sufficient to reach any campus. Galileo Galilei Airport (PSA) is Tuscany's major hub, located right next to the city (5 mins via Pisa Mover train).",
    climateAndVibe: "Ilıman Akdeniz iklimi; yazlar sıcak ve kurak, kışlar yumuşaktır. Şehir nüfusunun neredeyse yarısı öğrencilerden oluştuğu için benzersiz bir akademi ruhuna sahiptir. Arno Nehri kıyıları (Lungarno), akşamları öğrencilerin buluşma noktasıdır.",
    climateAndVibeEn: "Mild Mediterranean climate; hot, dry summers and mild winters. Students make up nearly half of the city's total population, creating a highly academic and energetic vibe. The Arno riverbanks (Lungarno) serve as the daily social hub for students.",
    editorialTip: "Pisa küçük ve düz bir şehir olduğu için evinizi nerede tutarsanız tutun kampüslere en fazla 15-20 dakika yürüme mesafesinde olursunuz. Pisa Mover veya otobüslere para harcamak yerine yürüyüşün tadını çıkarın.",
    editorialTipEn: "Pisa is flat and compact; no matter where you rent, your campus will be within a 15-20 min walk. Save money on transit and enjoy walking or cycling everywhere."
  },
  {
    slug: "siena",
    name: "Siena",
    nameEn: "Siena",
    region: "Toscana",
    costSourceName: "Numbeo",
    costSourceUrl: "https://www.numbeo.com/cost-of-living/in/Siena",
    costSourceLastUpdated: "2026-05-04",
    costRating: 3,
    studentPopulation: "Orta",
    studentPopulationEn: "Medium",
    rentAverage: "1 odalı daire: merkezde ~1.016,67€ | merkez dışında ~662,50€",
    rentAverageEn: "1-bedroom apartment: ~€1,016.67 in the city centre | ~€662.50 outside the centre",
    livingExpenses: "Ucuz restoran: ~14€ | Cappuccino: ~1,68€ | 85 m² temel faturalar: ~157,60€",
    livingExpensesEn: "Inexpensive meal: ~€14 | Cappuccino: ~€1.68 | Basic utilities for 85 m²: ~€157.60",
    transportCost: "Tek yön şehir içi bilet: ~1,70€",
    transportCostEn: "One-way local transport ticket: ~€1.70",
    transportDetails: "Şehir içi ulaşım otobüs hatları, yürüyüş ve tren istasyonu bağlantıları etrafında şekillenir. Tarihi merkez kompakt ama yokuşlu olduğu için ev seçerken kampüs ve günlük rota mesafesini birlikte değerlendirmek gerekir.",
    transportDetailsEn: "Local mobility is shaped around bus lines, walking, and rail-station connections. The historic centre is compact but hilly, so housing decisions should consider both campus access and everyday route effort.",
    climateAndVibe: "Toskana içinde tarihi dokusu çok güçlü, daha küçük ve odaklı bir öğrenci şehridir. Büyük şehir temposundan çok yerel mahalle yaşamı, turizm yoğunluğu ve sakin akademik rutin öne çıkar.",
    climateAndVibeEn: "Siena is a smaller, focused student city in Tuscany with a very strong historic character. Instead of big-city pace, daily life revolves around local neighborhoods, tourism pressure, and a calmer academic routine.",
    editorialTip: "Tarihi merkez çok çekici ama kira ve günlük ulaşım açısından her zaman en pratik seçenek olmayabilir. Merkez dışındaki evleri kampüs bağlantısı, otobüs hattı ve yokuş mesafesiyle birlikte kıyaslayın.",
    editorialTipEn: "The historic centre is attractive, but it may not always be the most practical option for rent and daily mobility. Compare outside-centre housing by campus access, bus routes, and the effort of hilly walks."
  },
  {
    slug: "pavia",
    name: "Pavia",
    nameEn: "Pavia",
    region: "Lombardia",
    costSourceName: "Numbeo",
    costSourceUrl: "https://www.numbeo.com/cost-of-living/in/Pavia",
    costSourceLastUpdated: "2026-05-04",
    costRating: 3,
    studentPopulation: "Orta (>25.000)",
    studentPopulationEn: "Medium (>25,000)",
    rentAverage: "1 odalı daire: merkezde ~578,50€ | merkez dışında ~452,25€",
    rentAverageEn: "1-bedroom apartment: ~€578.50 in the city centre | ~€452.25 outside the centre",
    livingExpenses: "Ucuz restoran: ~15€ | Cappuccino: ~1,53€ | 85 m² temel faturalar: ~179,35€",
    livingExpensesEn: "Inexpensive meal: ~€15 | Cappuccino: ~€1.53 | Basic utilities for 85 m²: ~€179.35",
    transportCost: "Tek yön şehir içi bilet: ~1,60€",
    transportCostEn: "One-way local transport ticket: ~€1.60",
    transportDetails: "Pavia içi ulaşım otobüslerle sağlanır. Şehir içi banliyö trenleriyle (S13 hattı) Milano merkezine (Rogoredo / Porta Venezia) sadece 30 dakikada doğrudan ulaşım mümkündür.",
    transportDetailsEn: "Local transit is served by Autoguidovie buses. Suburban train (S13 line) connects Pavia directly to central Milan in just 30 minutes, departing every 30 minutes.",
    climateAndVibe: "Karasal iklim özellikleri; kışları soğuk ve sisli, yazları sıcak geçer. İtalya'nın en prestijli tarihi üniversitelerinden birine ev sahipliği yapar. Ünlü 'Collegi' (üniversite kolejleri) sistemi sayesinde Oxford veya Cambridge benzeri çok güçlü bir yurt-kampüs kültürü mevcuttur. Sakin, güvenli ve samimidir.",
    climateAndVibeEn: "Continental climate; cold, foggy winters and hot summers. Home to one of Italy's most prestigious historic universities. Renowned for its unique Oxford-style 'Collegi' (collegiate residency system), fostering a tight-knit and traditional student community.",
    editorialTip: "Pavia Belediyesi ve toplu taşıma kurumu öğrencilere yıllık otobüs kartını sembolik olarak sadece 20€'ya vermektedir. Pavia'da yaşayıp Milano'daki sosyal hayatı banliyö treniyle takip etmek bütçeniz için harika bir formüldür.",
    editorialTipEn: "The local authority offers students an annual unlimited bus pass for a symbolic fee of just €20. Living in Pavia and commuting to Milan via the S13 train is an incredible money-saving life hack."
  },
  {
    slug: "trento",
    name: "Trento",
    nameEn: "Trento",
    region: "Trentino-Alto Adige",
    costRating: 3,
    studentPopulation: "Orta (>20.000)",
    studentPopulationEn: "Medium (>20,000)",
    rentAverage: "Tek kişilik oda: 350€ - 500€ | Stüdyo daire: 600€ - 850€",
    rentAverageEn: "Single room: €350 - €500 | Studio apartment: €600 - €850",
    livingExpenses: "Aylık 280€ - 370€ (Yüksek yaşam kalitesi standartları)",
    livingExpensesEn: "€280 - €370 monthly (High quality of life standard expenses)",
    transportCost: "Yıllık Trentino ulaşım kartı: 50€ (Öğrenci)",
    transportCostEn: "Annual Trentino student transit pass: €50",
    transportDetails: "Mükemmel işleyen temiz otobüs hatları ve dağlık bölgelere çıkan teleferikler. Yıllık öğrenci kartıyla tüm Trentino eyaletindeki trenler ve otobüsler ücretsizdir. Verona ve Bolzano şehirlerine trenle 45-50 dakikadır.",
    transportDetailsEn: "Superb, pristine bus network and mountain cable cars. The annual €50 student pass grants unlimited free access to all trains and buses across the entire Trentino province. Verona and Bolzano are 45-50 mins away via train.",
    climateAndVibe: "Alp iklimi. Kışlar oldukça soğuk, karlı ve kayak yapmaya elverişlidir. Yazlar serin ve temiz dağ havasıyla doludur. İtalya'nın en yüksek yaşam kalitesine, en temiz sokaklarına ve en iyi organize olmuş kamu hizmetlerine sahip şehridir. Doğa sporları, doğa yürüyüşü ve kayak tutkunları için bir cennettir.",
    climateAndVibeEn: "Alpine climate. Cold, snowy winters perfect for skiing; fresh, breezy summers with crisp mountain air. Officially ranked as Italy's top city for quality of life, public safety, and pristine environmental standards. A paradise for outdoor sports and hiking.",
    editorialTip: "Doğa ile iç içe, düzenli ve huzurlu bir eğitim hayatı arayanlar için İtalya'daki en kusursuz seçenektir. Yıllık 50€'luk kartınızı alır almaz tüm eyaleti (Garda Gölü dahil) trenle keşfetmeye başlayın.",
    editorialTipEn: "The ultimate choice for students seeking a highly organized, safe, and nature-surrounded lifestyle. Grab your €50 annual card immediately and explore the entire province, including Lake Garda, for free."
  },
  {
    slug: "trieste",
    name: "Trieste",
    nameEn: "Trieste",
    region: "Friuli-Venezia Giulia",
    costSourceName: "Numbeo",
    costSourceUrl: "https://www.numbeo.com/cost-of-living/in/Trieste",
    costSourceLastUpdated: "2026-05-13",
    costRating: 3,
    studentPopulation: "Orta",
    studentPopulationEn: "Medium",
    rentAverage: "1 odalı daire: merkezde ~727,50€ | merkez dışında ~588,33€",
    rentAverageEn: "1-bedroom apartment: ~€727.50 in the city centre | ~€588.33 outside the centre",
    livingExpenses: "Ucuz restoran: ~18€ | Cappuccino: ~1,92€ | 85 m² temel faturalar: ~194,47€",
    livingExpensesEn: "Inexpensive meal: ~€18 | Cappuccino: ~€1.92 | Basic utilities for 85 m²: ~€194.47",
    transportCost: "Tek yön şehir içi bilet: ~1,45€",
    transportCostEn: "One-way local transport ticket: ~€1.45",
    transportDetails: "Şehir içi ulaşım otobüs hatları, tren istasyonu ve kıyı hattı etrafında şekillenir. Merkez ile yamaç mahalleleri arasındaki günlük rotalarda eğim ve aktarma sürelerini hesaba katmak gerekir.",
    transportDetailsEn: "Local mobility is shaped around bus lines, the main rail station, and the waterfront. For daily routes between the centre and hillside neighborhoods, factor in slopes and transfer times.",
    climateAndVibe: "Adriyatik kıyısında, Orta Avrupa etkisi hissedilen sakin ve karakterli bir öğrenci şehridir. Deniz, tarihi kafe kültürü ve sınır bölgesi atmosferi büyük metropollerden farklı bir günlük ritim yaratır.",
    climateAndVibeEn: "Trieste is a calm and distinctive student city on the Adriatic, with a noticeable Central European influence. The sea, historic cafe culture, and border-region atmosphere create a daily rhythm unlike larger Italian metros.",
    editorialTip: "Ev bakarken merkeze yakınlık kadar otobüs hattı, tren istasyonu erişimi ve yokuş mesafesini de kontrol edin. Merkez dışı mahalleler bütçeyi rahatlatabilir ama günlük ulaşım süresini birlikte hesaplamak gerekir.",
    editorialTipEn: "When choosing housing, check bus access, station links, and hill distance as much as centrality. Outside-centre neighborhoods can help the budget, but daily travel time should be calculated carefully."
  },
  {
    slug: "bari",
    name: "Bari",
    nameEn: "Bari",
    region: "Puglia",
    costSourceName: "Numbeo",
    costSourceUrl: "https://www.numbeo.com/cost-of-living/in/Bari",
    costSourceLastUpdated: "2026-05-04",
    costRating: 2,
    studentPopulation: "Orta-Yüksek",
    studentPopulationEn: "Medium-High",
    rentAverage: "1 odalı daire: merkezde ~800€ | merkez dışında ~597,75€",
    rentAverageEn: "1-bedroom apartment: ~€800 in the city centre | ~€597.75 outside the centre",
    livingExpenses: "Ucuz restoran: ~15€ | Cappuccino: ~1,74€ | 85 m² temel faturalar: ~214,76€",
    livingExpensesEn: "Inexpensive meal: ~€15 | Cappuccino: ~€1.74 | Basic utilities for 85 m²: ~€214.76",
    transportCost: "Tek yön şehir içi bilet: ~1€",
    transportCostEn: "One-way local transport ticket: ~€1",
    transportDetails: "Şehir içi ulaşım ağırlıkla AMTAB otobüs hatlarıyla sağlanır. Bari Centrale, Puglia içindeki kıyı şehirlerine ve bölgesel bağlantılara açılan ana ulaşım merkezidir.",
    transportDetailsEn: "Local transit relies mostly on AMTAB bus lines. Bari Centrale is the main mobility hub for regional connections and nearby coastal towns across Puglia.",
    climateAndVibe: "Sıcak ve güneşli Akdeniz iklimine sahiptir. Adriyatik kıyısındaki şehir; tarihi Bari Vecchia, sahil yürüyüşleri ve yavaş tempolu güney yaşamıyla daha sakin bir öğrenci deneyimi sunar.",
    climateAndVibeEn: "Bari has a warm, sunny Mediterranean climate. Set on the Adriatic coast, it offers a calmer student experience shaped by Bari Vecchia, seaside walks, and the slower rhythm of southern Italy.",
    editorialTip: "Ev ararken kampüs, Bari Centrale ve otobüs hatları üçgenini birlikte düşünün. Eski şehir çok karakterlidir; günlük öğrenci hayatı için merkeze yakın ama daha sakin mahalleleri de kıyaslayın.",
    editorialTipEn: "When looking for housing, consider the triangle between your campus, Bari Centrale, and frequent bus routes. The old town is full of character, but quieter central neighborhoods can be easier for everyday student life."
  },
  {
    slug: "ancona",
    name: "Ancona",
    nameEn: "Ancona",
    region: "Marche",
    costSourceName: "Numbeo",
    costSourceUrl: "https://www.numbeo.com/cost-of-living/in/Ancona",
    costSourceLastUpdated: "2026-05-04",
    costRating: 2,
    studentPopulation: "Orta",
    studentPopulationEn: "Medium",
    rentAverage: "1 odalı daire: merkezde ~530€ | merkez dışında ~424€",
    rentAverageEn: "1-bedroom apartment: ~€530 in the city centre | ~€424 outside the centre",
    livingExpenses: "Ucuz restoran: ~15€ | Cappuccino: ~1,77€ | 85 m² temel faturalar: ~247€",
    livingExpensesEn: "Inexpensive meal: ~€15 | Cappuccino: ~€1.77 | Basic utilities for 85 m²: ~€247",
    transportCost: "Tek yön şehir içi bilet: ~1,50€",
    transportCostEn: "One-way local transport ticket: ~€1.50",
    transportDetails: "Şehir içi ulaşım otobüs hatları ve tren istasyonu etrafındaki bölgesel bağlantılarla ilerler. Liman, merkez ve kampüs hattı arasında günlük rotayı önceden kontrol etmek faydalıdır.",
    transportDetailsEn: "Local mobility is built around bus lines and regional rail connections near the main station. It is worth checking the daily route between the port area, the centre, and campus before choosing housing.",
    climateAndVibe: "Adriyatik kıyısında yer alan Ancona, daha sakin ve kompakt bir öğrenci hayatı sunar. Büyük metropollere göre daha yerel, denizle iç içe ve pratik bir şehir deneyimi beklemek gerekir.",
    climateAndVibeEn: "Set on the Adriatic coast, Ancona offers a calmer and more compact student life. Compared with large metropolitan cities, expect a more local, seaside-oriented, and practical daily rhythm.",
    editorialTip: "Ancona'da ev seçerken merkeze uzaklıktan çok kampüs ve otobüs bağlantısını kontrol edin. Şehir yamaçlı bölgeler içerdiği için haritadaki mesafe ile günlük yürüyüş süresi aynı hissettirmeyebilir.",
    editorialTipEn: "In Ancona, check campus and bus access before judging a place only by centrality. The city includes hilly areas, so map distance and actual walking time can feel quite different."
  },
  {
    slug: "napoli",
    name: "Napoli",
    nameEn: "Naples",
    region: "Campania",
    costSourceName: "Numbeo",
    costSourceUrl: "https://www.numbeo.com/cost-of-living/in/Naples",
    costSourceLastUpdated: "2026-05-14",
    costRating: 2,
    studentPopulation: "Çok Yüksek",
    studentPopulationEn: "Very High",
    rentAverage: "1 odalı daire: merkezde ~966€ | merkez dışında ~612,20€",
    rentAverageEn: "1-bedroom apartment: ~€966 in the city centre | ~€612.20 outside the centre",
    livingExpenses: "Ucuz restoran: ~15,50€ | Cappuccino: ~1,94€ | 85 m² temel faturalar: ~188,48€",
    livingExpensesEn: "Inexpensive meal: ~€15.50 | Cappuccino: ~€1.94 | Basic utilities for 85 m²: ~€188.48",
    transportCost: "Tek yön şehir içi bilet: ~1,50€",
    transportCostEn: "One-way local transport ticket: ~€1.50",
    transportDetails: "Şehir içi ulaşım metro, füniküler, otobüs ve banliyö tren hatlarının birleşimiyle çalışır. Merkez, sahil hattı ve tepe mahalleleri arasında rota planlarken aktarmaları hesaba katmak gerekir.",
    transportDetailsEn: "Local mobility combines metro, funiculars, buses, and suburban rail. Plan transfers carefully when moving between the historic centre, the waterfront, and hill neighborhoods.",
    climateAndVibe: "Sıcak Akdeniz iklimi, yoğun sokak hayatı ve güçlü yemek kültürüyle Napoli çok canlı bir öğrenci şehridir. Ritim hızlı ve yer yer kaotiktir; buna alışınca şehir oldukça karakterli ve erişilebilir bir deneyim sunar.",
    climateAndVibeEn: "Naples is a vivid student city shaped by a warm Mediterranean climate, intense street life, and a strong food culture. Its rhythm can feel fast and chaotic, but it rewards students with character and accessibility.",
    editorialTip: "Ev bakarken sadece merkeze değil, günlük ulaşım hattınıza ve mahallenin gece/sabah ritmine de bakın. Füniküler veya metroya yakın bir konum, şehir deneyimini ciddi şekilde kolaylaştırır.",
    editorialTipEn: "When choosing housing, look beyond centrality: check your daily transit route and the neighborhood rhythm at night and early morning. Being close to a funicular or metro stop can make everyday life much easier."
  }
];

export function getCityDetailBySlug(slug: string): CityDetail | undefined {
  const normalized = slug.toLowerCase().trim();
  return CURATED_CITIES.find((c) => c.slug === normalized);
}

export function getCityDetailByName(name: string): CityDetail | undefined {
  const normalized = name.toLowerCase().trim();
  return CURATED_CITIES.find(
    (c) =>
      c.name.toLowerCase().trim() === normalized ||
      c.nameEn.toLowerCase().trim() === normalized ||
      c.slug === normalized
  );
}

export function getFallbackCityDetail(cityName: string, universityCount: number, regionName: string): CityDetail {
  const slug = cityName.toLowerCase().replace(/[^a-z0-9]+/g, "-");
  return {
    slug,
    name: cityName,
    nameEn: cityName,
    region: regionName,
    costRating: 3,
    studentPopulation: "Orta",
    studentPopulationEn: "Medium",
    rentAverage: "Tek kişilik oda: 300€ - 450€ | Stüdyo: 500€ - 750€",
    rentAverageEn: "Single room: €300 - €450 | Studio: €500 - €750",
    livingExpenses: "Aylık 220€ - 300€ (Sakin yerel mutfak alışverişi)",
    livingExpensesEn: "€220 - €300 monthly (Local grocery and student dining)",
    transportCost: "Aylık kart: 20€ - 30€",
    transportCostEn: "Monthly pass: €20 - €30",
    transportDetails: "Şehir içi otobüs hatları ve yerel banliyö trenleri mevcuttur.",
    transportDetailsEn: "Local bus lines and regional train networks serve the city.",
    climateAndVibe: `${cityName}, İtalya'nın ${regionName} bölgesinde yer alan, ${universityCount} üniversiteye ev sahipliği yapan tarihi bir şehirdir. Sakin, güvenli ve otantik bir İtalyan yaşam deneyimi sunar.`,
    climateAndVibeEn: `${cityName} is a historic Italian city located in the ${regionName} region, hosting ${universityCount} university. It offers a peaceful, secure, and highly authentic Italian living experience.`,
    editorialTip: "Bu şehir için editoryal detaylar henüz tasarım aşamasındadır. Şehirdeki üniversiteleri ve bölgeye ait resmi burs detaylarını haritamız üzerinden hemen inceleyebilirsiniz.",
    editorialTipEn: "Editorial details for this city are currently under development. You can explore the active universities and check regional scholarship thresholds immediately."
  };
}
